server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
spring:
  application:
    name: movement-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movement-service?zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=UTC
    username: root
    password: Lucas2012
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: movement-service
    user: root
    password: Lucas2012  
